### ISSUE TITLE
gradle build for bootRun freezes

### ISSUE THREAD

**Issue by iman-badr** [Open-MBEE/exec-mms#128]
Hello,
I have followed the instructions for running mms. After running the 3 docker images, I ran the command ./gradlew bootRun. However, the build seems to freeze. It takes more than 13 hours with the same message. I had one small change which is that I ran postgres at port 5433 instead of 5432 via the following command
docker run -d -e POSTGRES_PASSWORD=test1234 -e POSTGRES_USER=mmsuser -e POSTGRES_DB=mms -p 5433:5432 postgres:11-alpine 
and changed the port at the application properties accordingly
Here is what I get at git bash when running the gradle build
![grafik](https://user-images.githubusercontent.com/72130505/101458265-f5376e80-3936-11eb-8c72-d199df4060b9.png)

![grafik](https://user-images.githubusercontent.com/72130505/101469924-a0e7bb00-3945-11eb-8247-3140c738869d.png)

**Comment by HuiJun** [comment]
Hi there,

The first screenshot shows a normal execution with the bootRun gradle task. The task will never complete normally because it is starting a server and listening to the configured port. You can test it out by going to (according to the screenshot) http://localhost:8080/v3/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config (redirected from http://localhost:8080/v3/swagger-ui.html) to view the swagger-ui, which I am guessing you did, as the second screenshot seems to be originating from the initial call to that path. We are unsure why this happens on initial generation of the swagger file, but simply reloading should resolve your issue. From there, you should be able to test out the instance using the swagger-ui.

**Comment by iman-badr** [comment]
Thank you @HuiJun for the reply. Now the link works. It seems there was a problem with my application.properties file. Besides, I was misslead by the message which says that the progress is 98%.
Another issue which I am fassing is with the authentication. When trying to login to MMS from the Cameo plugin OpenMBEE-MDK. I write as url http://localhost:8080 and give username as test and password test, which are already in the application.properties but I get an error
![grafik](https://user-images.githubusercontent.com/72130505/101528363-82a6ad00-398f-11eb-9644-825c9ef9b86a.png)

![grafik](https://user-images.githubusercontent.com/72130505/101528452-a10ca880-398f-11eb-8968-a7e41c92105d.png)
![grafik](https://user-images.githubusercontent.com/72130505/101528554-c3062b00-398f-11eb-8094-e2a419e2e598.png)

![grafik](https://user-images.githubusercontent.com/72130505/101528647-dc0edc00-398f-11eb-83c7-023e27b716ca.png)

**Comment by HuiJun** [comment]
Are you using a build of the Cameo MDK that is compatible with MMS4? I may have stale information, but I believe that version is still in a snapshot and not a release. If you're using a snapshot, can you provide the logs so that I can pass it on to the correct contacts?

**Comment by iman-badr** [comment]
@HuiJun thank you for your feedback and sorry for my late reply because of vacations. The version I am using for MDK is 4.4.2-snapshot
Where can I get the logs

**Comment by iman-badr** [comment]
I have upgraded to 5.0.0-rc1 and still the problem persists. @HuiJun here is the log that I could find. I hope this makes the problem clearer

![grafik](https://user-images.githubusercontent.com/72130505/104214349-9a160180-5437-11eb-8d5d-c08b2033c141.png)

**Comment by HuiJun** [comment]
@iman-badr Sorry for the delay, but the logs indicate that this is an SSL error. Can you try connecting to the instance without ssl first?
